# This is a basic workflow to help you get started with Actions

name: CIBuild
resources:
  repositories:
    - repository: 'CICD' # Name of the repository
      type: github # github for GitHub repo's git for ADO repo's
      endpoint: PO_API # name of the ado service connection
      name: 'Davin-NBA/CICD' # org/repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  - template: template/template.yml@CICD

