resources:
  repositories:
    - repository: CICD
      type: git
      name: 'Davin-NBA/CICD'  # Name of the Build repository
      endpoint: 'Davin-NBA' # Name of the service connection

stages:
- stage: InheritStage
  jobs:
  - template: template/template.yml@CICD  # Reference gaming.yml from the Build repository
